config/routes.rb
Rails.application.routes.draw do

  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  #get 'sessions/new'
  resources :orders
  resources :payments
  resources :products
  resources :customers
  resources :suppliers
  resources :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'static#index'

  get    '/login',   to: 'sessions#new'
  get    '/clients', to: 'static#clients'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/api' => redirect('/swagger/dist/index.html?url=/api-docs.json')

end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :User
  has_many :orders
  validates :Customer_id, presence: true, uniqueness: true
  
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: %i[ show edit update destroy ]
  swagger_controller :customers, 'Customers'
  

  # GET /customers or /customers.json
  swagger_api :index do
    summary 'Returns all customers'
    notes 'Notes...'
  end
  def index
    @customers = Customer.all
  end

  # GET /customers/1 or /customers/1.json
  swagger_api :show do
    summary 'Returns one customer'
    param :path, :id, :integer, :required, "Customer id"
    notes 'Notes...'
  end
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers or /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: "Customer was successfully created." }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1 or /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: "Customer was successfully updated." }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1 or /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: "Customer was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:Customer_id, :User_id, :First_Name, :Last_Name, :Phone, :Address_1, :Address_2, :City, :Postal_Code)
    end
  
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_with(model: customer) do |form| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
        <% customer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Customer_id %>
    <%= form.number_field :Customer_id %>
  </div>

  <div class="field">
    <%= form.label :User_id %>
    <%= form.text_field :User_id %>
  </div>

  <div class="field">
    <%= form.label :First_Name %>
    <%= form.text_field :First_Name %>
  </div>

  <div class="field">
    <%= form.label :Last_Name %>
    <%= form.text_field :Last_Name %>
  </div>

  <div class="field">
    <%= form.label :Phone %>
    <%= form.number_field :Phone %>
  </div>

  <div class="field">
    <%= form.label :Address_1 %>
    <%= form.text_field :Address_1 %>
  </div>

  <div class="field">
    <%= form.label :Address_2 %>
    <%= form.text_field :Address_2 %>
  </div>

  <div class="field">
    <%= form.label :City %>
    <%= form.text_field :City %>
  </div>

  <div class="field">
    <%= form.label :Postal_Code %>
    <%= form.number_field :Postal_Code %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customers</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>User</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Phone</th>
      <th>Address 1</th>
      <th>Address 2</th>
      <th>City</th>
      <th>Postal code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.Customer_id %></td>
        <td><%= customer.User_id %></td>
        <td><%= customer.First_Name %></td>
        <td><%= customer.Last_Name %></td>
        <td><%= customer.Phone %></td>
        <td><%= customer.Address_1 %></td>
        <td><%= customer.Address_2 %></td>
        <td><%= customer.City %></td>
        <td><%= customer.Postal_Code %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @customer.Customer_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @customer.User_id %>
</p>

<p>
  <strong>First name:</strong>
  <%= @customer.First_Name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @customer.Last_Name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @customer.Phone %>
</p>

<p>
  <strong>Address 1:</strong>
  <%= @customer.Address_1 %>
</p>

<p>
  <strong>Address 2:</strong>
  <%= @customer.Address_2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @customer.City %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @customer.Postal_Code %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>